### ISSUE TITLE
Stroke starts too early in Firefox

### ISSUE THREAD

**Issue by Connum** [parsimonhi/animCJK#3]
Hi there,

nice work! I started something similiar some months ago (https://sino.constantinmedia.com/stroke-order/) but didn't get very far - SVG creation was just too tedious and I didn't have the time...

Just wanted to let you know that in Firefox, the strokes start too early, so for every stroke, there is a small red portion where the stroke begins, from the beginning of the animation. This doesn't happen in Chrome, however.

**Comment by parsimonhi** [comment]
Hello,

Thank you for your report.

I also noticed that bug recently. It seems it was not there using some previous versions of firefox on Windows, but i am not sure of that because i work on MacOS most of the time.  The bug is not visible using firefox on MacOS.

For those who want to fix this firefox bug on Windows "as soon as possible, replace for instance in the css of the svg files

	from {
		stroke:#c00;
		stroke-dashoffset:3334;
	}

by

	from {
		stroke:#ccc;
		stroke-dashoffset:3334;
	}
	5% {
		stroke:#c00;
		stroke-dashoffset:3334;
	}

**Comment by parsimonhi** [comment]
Hello,

I updated all the svgs by replacing:

from {
	stroke:#c00;
	stroke-dashoffset:3334;
}

by

from {
	stroke:#ccc;
	stroke-dashoffset:3334;
}
1% {
	stroke:#c00;
	stroke-dashoffset:3334;
}

**Comment by Connum** [comment]
That's great, thanks!
