### ISSUE TITLE
some radicals appear non-standard

### ISSUE THREAD

**Issue by diceoh** [parsimonhi/animCJK#39]
Hi, I noticed that the Japanese characters used in this set use the Kaishotai format for the 糸 radical (e.g. see 約). Was this an intentional choice? While not technically incorrect it is notably different from how it's generally written in most contexts in Japan. E.g. see Mincho, Gothic, Kyokasho styles here: https://kanji.jitenon.jp/kanjib/619.html

**Comment by parsimonhi** [comment]
Yes, AnimCJK uses the kaisho style. This is an intentional choice for several reasons.

1) We wanted the same font style for Chinese, Japanese, and Korean. It would have been difficult to choose any other style than the kaisho style to do this.

2) At the start of the animCJK project, we reused work from the remarkable [MakeMeAHanzi](https://github.com/skishore/makemeahanzi) project that had already been done for Chinese, and which uses the kaisho style.

3) The fonts that were chosen (by the author of the MakeMeAHanzi project) to create the characters are kaisho style fonts (Arphic PL KaitiM GB and Arphic PL UKai fonts).

The advantage of these fonts is that we can use and modify them without having copyright issues.

The downside is that these are fonts made for Chinese only. This is why regarding Japanese (and Korean) many modifications in the character glyphs had to be made in animCJK.

And in Kaisho style, even in Japanese, the radical 糸 is written as we did.

Note: we also made many changes for Chinese in animCJK compared to MakeMeAHanzi (missing characters, fixing errors, improving character glyphs, etc.)

**Comment by talutalu** [comment]
Hi, I'm the developer of the Android app that started that discussion.

I wanted to thank you for your answer and thanks a lot for this project that make it simple to select and animate different parts of a kanji.

Happy new year and a I wish you a lot of success for your next projects!

**Comment by parsimonhi** [comment]
Happy new year too!
