### ISSUE TITLE
Using animCJK Japanese data in Hanzi Writer

### ISSUE THREAD

**Issue by chanind** [parsimonhi/animCJK#6]
Hi - I maintain a project called [Hanzi Writer](https://github.com/chanind/hanzi-writer) for animating Chinese characters using the same MakeMeAHanzi data that animCJK uses. I set up a repo which pulls in the Japanese data from animCJK in a format that Hanzi Writer can use, currently at https://github.com/chanind/hanzi-writer-data-jp. Is the way this is set up OK with licensing and attribution and everything? If it seems to work well I'd like to add Japanese as an option to Hanzi Writer directly as well using this data. I'll add attribution to the repo and docs for Hanzi Writer back to animCJK as well of course.

Thanks for publishing the Japanese version of this data! It looks like it's really great quality!

**Comment by parsimonhi** [comment]
Hi - I know Hanzi Writer: great job!

Concerning licences for animCJK data:
- Kanji are licensed under Arphic license because at the beginning, I used MakeMeAHanzi data or parts of MakeMeAHanzi data to build them. Note that I also extracted some characters from Arphic fonts when there were not in Make Me A Hanzi. Of course I modified or built from scratch many characters. But it was too complicated to use another licence for these characters only, so I kept Arphic licence for these additional characters.

- Hiragana and Katakana have nothing in common with Arphic data and can be easily separated from the kanjis. This is the reason why I licensed them under LGPL license which is more permissive than the Arphic license.

It seems that you didn't include Hiragana and Katakana, so I think that you can just keep Arphic license at the moment.

**Comment by chanind** [comment]
Excellent! That makes this easy then. I don't think hiragana would work with Hanzi Writer in its current form anyway since it has strokes that loop back over themselves. Thanks so much! And awesome work with this library!
