### ISSUE TITLE
Different colour for each stroke ?

### ISSUE THREAD

**Issue by TotalCoolness** [parsimonhi/animCJK#7]
Would it be possible to have each stroke a different colour, like for example:

https://github.com/cayennes/kanji-colorize

and have it exported into animatedGIF to use in anki !

**Comment by parsimonhi** [comment]
It is possible, using a code similar to http://gooo.free.fr/animCJK/official/samples/red.php.

**Comment by TotalCoolness** [comment]
Oh I didn't know Anki supported svgs animations (I thought they were static svg).

Yes, animated colored kanji with stroke numbers. I couldn't find any.

**Comment by parsimonhi** [comment]
You can try the following (let me know if it works for you):<br><br>First step<br>1) Using a browser, go to http://gooo.free.fr/animCJK/official/samples/<br>2) Select the "rainbow" sample<br>3) Enter a kanji in the box which is on the left of the "Display" button<br>4) Click on the "Display" button<br>5) At this point, you should see an animation displaying the character you entered. The corresponding code is displayed in the "SVG Code" box at the bottom of the page. Select this code using the mouse and copy it (using for instance Cmd C or Ctrl C)<br><br>Second Step<br>1) Open Anki<br>2) Edit the convenient card<br>3) Click on the field of the card (or add one) where you want to insert the character<br>4) Select in the menu "Modify HTML" or something like that (possibly by clicking in the "hamburger" menu on the right of the editor). A window should appears<br>5) Paste in the html code, at the place where you want the character should be, the SVG code of the character you previously copied<br><br>Say a prayer and it should work!

**Comment by TotalCoolness** [comment]
Thanks worked perfectly! Looks much better than the ugly animated GIFs.

I didn't see that "rainbow" option when I downloaded it.

The only problem is doing this 3,000 times in Heisigs RTK (6th edition) order is not really feasible.. anyway to automate it ?

**Comment by parsimonhi** [comment]
You didn't see the "rainbow" option because i made it last night! :-)!<br><br> I will add it to the next github repository update.<br><br>I don't know how to automate an update of the Heisigs RTK (I am not an expert of Anki, but it's probably feasible). Can you tell me where to find the version you are using? (I found some but i would be sure that I got the right one)

**Comment by TotalCoolness** [comment]
This is the deck: https://ankiweb.net/shared/info/702183246

2,200 Kanji from RTK Volume 1 of the book 1.
800 from RTK book 3.

What you can do to add them is use this plugin to help import / export CSV : 
https://ankiweb.net/shared/info/1478130872

Create a new field in the deck called SVGanimated to be the target field.

Just export three fields something like: FrameNumV6, kanji, SVGanimated 

The first field in the CSV file is very important and when importing since it has to match for updating the fields. You could actually have the first field the kanji and let it match that way.

Go to Browser in Anki "Fields" and reposition the FrameNumV6 (or kanji) field to be position 1. 

Now all we need is you to put that SVG animated kanji data in that blank field... and IMPORT :)

**Comment by parsimonhi** [comment]
Thanks you for these informations. I will try to automate the process. But I don't know how many time it will be necessary to make the code because I am nearly a newbie in anki.

**Comment by edberteliezer** [comment]
@parsimonhi First I want to ask why don't you use Array.from instead of magic string to array. Second, I have an idea about anki. You can include a library of svgs in the anki installation folder. I have seen an addon where user need to download the library separately #because anki server are not that good to download large library from, and the addon only include needed files to user media folder. #because user media folder will be synced and uploaded to anki. So the scenario is 

1optionA. Have user uses predetermined notes name 
# notes name is like an html file it has <head> and html for front of card and back of card. 
# predetermined note name because you don't want the addon to be active everywhere. 
1optionB. use a button some add on has that, to target active input field, and use it as target string you want to convert to unicode code points. 
2. Find a way to do codePointAt in python and save the string in a variable. 
3. do a copy command from svg library to user's media #the one that is synced to anki server.  if duplicate, cancel the operation or force duplicate because it won't matter if have the same file name(? i think). 
4. fill in <img src:field.codePointAt /> to a predetermined field name 
#this is anki default attach and image behaviour I am not sure anki attach as string or not pls investigate more. 
5. Lastly, you can set field names as variable so users can edit the python files. but if you are feeling kind make a gui for native anki configuration file 
I am trying to learn python tomorrow just to code this functionality but I don't know python so sad. If you can make it for us that would be awesome.

**Comment by edberteliezer** [comment]
@parsimonhi apparently to modify svg inside an iframe requires local server. I don't think anki run on local server, you will have to dynamically modify --d values of svg with python then inline the data to anki if we want to use the 'several' or 'colored line' version of anim cjk however I do have a way to color the animation without the need to access iframe. Please contact me if want to make the anki add on I will provide you the way to color the stroke without accessing iframe window.

**Comment by parsimonhi** [comment]
@TotalCoolness

Never too late! :-)

Here is what you can do:

1) copy as is the svgsJa folder in the anki files collection (see https://docs.ankiweb.net/files.html for more details if you don't know where is your files collection). At this point, svgsJa should be a subfolder of the folder where the anki files collection is.
2) open anki
3) browse your deck
4) click on "Card" button to edit the code of a card template
5) replace in the code of the card {{StrokesGIF}} by the following code (or add this code anywhere you want the svg will appear, or create a field called SVGanimated which contains this code and add anywhere in the card template {{SVGanimated}}, or create an import procedure which will create this field in all the cards and add anywhere in the card template {{SVGanimated}})
`<span class="svgContainer"></span>` 
6) add at the bottom of the code of the card template:
`<script>
  let source=document.querySelector('.huge');
  if(source)
  {
    let char=source.innerHTML;
    let code=char.codePointAt(0);
    let target=document.querySelector('.svgContainer');
    if(code&&target)
      target.innerHTML='<img src="svgsJa/'+code+'.svg">';
  }
</script>`

Hope it helps!
